### ISSUE TITLE
Investigate nil'ing out undesired `:customize` attributes

### ISSUE THREAD

**Issue by fnichol** [test-kitchen/kitchen-vagrant#132]
Here is an abbreviated example:

A `.kitchen.yml`:

``` yaml

---
driver:
  name: vagrant
  provider: vmware_fusion
  customize:
    numvcpus: 2
    memsize: 2048
```

and a `.kitchen.local.yml`:

``` yaml

---
driver:
  name: vagrant
  provider: virtualbox
  customize:
    cpus: 2
    memsize: 2048
```

This leads to a combined configuration of:

``` yaml

---
driver:
  name: vagrant
  provider: virtualbox
  customize:
    cpus: 2
    numvcpus: 2
    memsize: 2048
```

And passing `numvcups` into the VirtualBox provider configuration won't work (it's a VMware configuration attribute).

One possible solution could be to "nill out" undersired values in the `:customize` block like so (using the `.kitchen.local.yml` example from above):

``` yaml

---
driver:
  name: vagrant
  provider: virtualbox
  customize:
    cpus: 2
    numvcpus: nil
    memsize: 2048
```

The result would cause the Vagrantfile to drop the `numvcpus` attribute and lead to a workable configuration.

This may not be ideal, and there could be legitimate reasons for setting a `nil` value which is why it deserves a touch of exploration first. Anyway, parking this here :wink:
