### ISSUE TITLE
[Feature Request] Updating vagrant box

### ISSUE THREAD

**Issue by yves-vogl** [test-kitchen/kitchen-vagrant#138]
Hi,

I'd like to implement updating a vagrant box automatically if a newer one exists.

```
       ==> default: have version '1.1.0'. The latest is version '1.1.1'. Run
       ==> default: `vagrant box update` to update.
```

It could look like:

```
driver_config:
      box: example/centos6
      box_url: http://example.com/centos6.json
      version: <version>
```

_version_ may be "latest" or an optionally prefixed (>, <, ~>, >=, <=) version description.

What do you think?
