### ISSUE TITLE
Default settings overriding vm_hostname?  Or configured incorrectly?

### ISSUE THREAD

**Issue by Joseph-R** [test-kitchen/kitchen-vagrant#139]
I want to set a vm_hostname in the .kitchen.yml and have that picked up by Ohai and fed to my Chef recipes via the automatic attribute 'hostname'.

So far, attempts to set vm_hostname to 'dbserver.local' result in "dbserver-$OS-$version".  This leads me to believe that my vm_hostname settings are either being overwritten by the default or are simply not being applied correctly.  

**Use case:** 
Trying to test an application with two servers, an app server and a DB, that need to talk to each other over the local network in my development environment.  We are using $hostname.local entries in /etc/hosts to simulate DNS.  So appserver.local, dbserver.local, etc.  I need to set the hostname entries in the VM to ensure that hostname and FQDN entries remain static and consistent while testing across different operating systems and versions.

**.kitchen.yml**
```
---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.8.0
  (snip $paths)

platforms:
  - name: centos-6.5
    driver_config:
      box: centos_65
      box_url: https://s3.amazonaws.com/o2o-public/centos_6.5_x86_64_provisionerless.box
  - name: centos-5.10
    driver_config:
      box: centos_510
      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-5.10-i386_chef-provisionerless.box
      
suites:
  - name: analytics
    driver:
      vm_hostname: analytics.local
      network:
      - ["private_network", {ip: "33.33.33.110"}]
      - ["forwarded_port", {guest: 9292, host: 9292}] # app
      - ["forwarded_port", {guest: 3002, host: 3002}] # app2
      - ["forwarded_port", {guest: 10001, host: 10001}] # app3
      synced_folders:
      - ["~/repo/dir", "/dir", "create: true, type: :nfs"]
      - ["~/repo2/dir", "/dir", "create: true, type: :nfs"]
      customize:
        memory: 1024
    run_list:
      - recipe[JO2O]
      - role[app]
    excludes: ["centos-6.5"]
    attributes:
      remote_user: <%= ENV['USER'] %>
      public_ipaddress: "33.33.33.110"
      iptables:
        install_rules: false

  - name: dbserver
      driver:
        vm_hostname: dbserver.local
        network:
        - ["private_network", {ip: "33.33.33.111"}]
        - ["forwarded_port", {guest: 2181, host: 2181}] # app3
        - ["forwarded_port", {guest: 8020, host: 8020}] # app4
        synced_folders:
        - ["~/repo/dir", "/dir", "create: true, type: :nfs"]
        customize:
          memory: 4096
      run_list:
        - recipe[JO2O]
        - role[db]
      excludes: ["centos-5.10"]
      attributes:
        remote_user: <%= ENV['USER'] %>
        public_ipaddress: "33.33.33.111"
        iptables:
          install_rules: false
```

**This generates the following Vagrantfile, for the dbserver:**
```
Vagrant.configure("2") do |c|
  c.vm.box = "centos_65"
  c.vm.box_url = "https://s3.amazonaws.com/o2o-public/centos_6.5_x86_64_provisionerless.box"
  c.vm.hostname = "dbserver.local"
  c.vm.network(:private_network, {:ip=>"33.33.33.111"})
  c.vm.network(:forwarded_port, {:guest=>2181, :host=>2181})
  c.vm.network(:forwarded_port, {:guest=>8020, :host=>8020})
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "/Users/jreid/repo/O2O", "/home/adsummos/analytics", create: true, type: :nfs
  c.vm.provider :virtualbox do |p|
    p.customize ["modifyvm", :id, "--memory", "4096"]
  end
end
```

But attempts to use the Ohai automatic attribute 'hostname' in Chef result in "dbserver-$OS-$version".

**Template to test output:**
```
Hostname: <%= node['hostname'] %>
Domain: <%= node['domain'] %>
FQDN: <%= node['fqdn'] %>
IP:<%= node['ipaddress'] %>
Private network: <%= node['private_network'] %>
Public IP: <%= node['public_ip'] %>
Private IP: <%= node['private_ip'] %>
Coded public_ipaddress attribute: <%= node['public_ipaddress'] %>
```

**Results after successful `kitchen converge`:**
```
Hostname: dbserver-centos-65       # Expecting: dbserver
Domain: local
FQDN: dbserver.local
IP:10.0.2.15
Private network:
Public IP:
Private IP:
Coded public_ipaddress attribute: 33.33.33.111
```

**Versions:**
*  Mac OSX: 10.9.4
*  Vagrant: 1.7.2
*  Chef Development Kit Version: 0.3.5
*  Test Kitchen version 1.2.1
*  Gems - chef-provisioning-vagrant (0.8.1), kitchen-vagrant (0.15.0)

The Vagrantfile generated for these VMs looks correct.  Why isn't it being correctly passed to the node?  Is there something we need to do different?

Regards,
Joe Reid

**Comment by JoeReid-Korrelate** [comment]
I attempted to move the problem away from Vagrant and Kitchen altogether.  

Interestingly, attempts to use the [hostname cookbook](https://github.com/3ofcoins/chef-cookbook-hostname) set the hostname and FQDN correctly, but generated problems in the /etc/hosts file.  That's because it depends on the [hostsfile](https://github.com/customink-webops/hostsfile) cookbook, and at [some point it ignores the hostname you've set through code and reloads the Ohai attribute 'hostname'](https://github.com/3ofcoins/chef-cookbook-hostname/blob/develop/recipes/default.rb).

I think any workaround is going to be problematic if we're constantly dueling test-kitchen for control of the automatic attribute 'hostname'.

**Comment by Joseph-R** [comment]
Hey guys!  Any update or feedback on this ticket?

**Comment by cheeseplus** [comment]
I've attempted to repro the first report and can't seem to with current versions:

ChefDK 0.10.0
kitchen 1.4.2
Vagrant 1.8.1
kitchen-vagrant 0.19.0
Chef 12.6.0 / ohai 

**.kitchen.yml**

```
---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: centos-7.1

suites:
  - name: default
    driver:
      vm_hostname: bowie.local
    run_list:
    attributes:
```

**Vagrantfile**
```
Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "opscode-centos-7.1"
  c.vm.box_url = "https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.1_chef-provisionerless.box"
  c.vm.hostname = "bowie.local"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
  end
end
```

** node['hostname'] **

```
[vagrant@bowie ~]$ ohai hostname
[
  "bowie"
]
```

** node['fqdn'] **

```
[vagrant@bowie ~]$ ohai fqdn
[
  "bowie.local"
]
```

**/etc/hosts**

```
[vagrant@bowie ~]$ cat /etc/hosts
127.0.0.1   bowie.local bowie localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
```

**Comment by cheeseplus** [comment]
Closing this for no feedback - feel free to re-open if still an issue.

**Comment by justsee** [comment]
@Joseph-R - setting the hostname will initially work, but any Chef recipe relying on `node_name` will pick up the default generated one unless you specify one in a [client_rb](https://github.com/test-kitchen/test-kitchen/issues/340#issuecomment-34582865) or [solo_rb](https://github.com/test-kitchen/test-kitchen/issues/199#issuecomment-39164874) block in `kitchen.yml`

```
---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  json_attributes: false
  data_bags_path: '../../chef-server/data_bags'
  environments_path: '../../chef-server/environments'
  encrypted_data_bag_secret_key_path: '/etc/chef/databags.pem'
  client_rb:
    node_name: analytics.local
```
