### ISSUE TITLE
Customize does not support OpenStack provider

### ISSUE THREAD

**Issue by xmik** [test-kitchen/kitchen-vagrant#171]
A Hash of customizations to a Vagrant virtual machine supports some Vagrant providers, e.g. it does not support `openstack` provider. Real use case: when I set in .kitchen.yml:
```
    driver_config:
      box:	'debian-7.5-chef-11.16.4'
      ssh_key: '~/.ssh/id_rsa'
      customize:
        keypair_name: 'my-ssh-key'
```
The generated Vagrantfile should contain
```
  c.vm.provider :openstack do |p|
      p.keypair_name = "my-ssh-key"
  end
```
but instead it does:
```
  c.vm.provider :openstack do |p|
  end
```
