### ISSUE TITLE
Cannot manage Ubuntu 12.04 and 14.04 concurrently

### ISSUE THREAD

**Issue by tpetchel** [test-kitchen/kitchen-vagrant#173]
@fnichol this is the issue I mentioned to you.

## Scenario

Converging a 12.04 and 14.04 instance concurrently places the 14.04 instance in an inoperable state.

## Environment

Host: Ubuntu 14.04, running through Fusion with VT-x/EPT enabled.

```
$ vagrant --version
Vagrant 1.7.2
$ VBoxManage --version
4.3.26r98988
$ chef --version
Chef Development Kit Version: 0.5.1
chef-client version: 12.3.0
berks version: 3.2.3
kitchen version: 1.4.0
```

## Repro steps

1. Create a cookbook.

  ```
$ chef generate cookbook foo
```

1. Modify `.kitchen.yml` to include 12.04 and 14.04.

  ```
---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    driver:
      box: opscode-ubuntu-14.04
      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box
  - name: ubuntu-12.04
    driver:
      box: opscode-ubuntu-12.04
      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box

suites:
  - name: default
    run_list:
      - recipe[foo::default]
    attributes:
```

1. Create the instances

  ```
$ kitchen create
```

  The output from this command is here: https://gist.github.com/tpetchel/c4fb4215085dc9022e1a#file-create-txt

1. Login to each instance  

  Note that you can successfully log in to both instances.

1. Converge the instances

  ```
$ kitchen converge
```

  The output from this command is here: https://gist.github.com/tpetchel/c4fb4215085dc9022e1a#file-converge-txt.

1. Login to each instance

## Expected result

You should be able to login to both instances.

## Actual result

You can login to the 12.04 instance, but not the 14.04 instance.

```
$ kitchen login default-ubuntu-1404
ssh: connect to host 127.0.0.1 port 2222: Connection refused
```

VirtualBox shows the 14.04 instance as Aborted.

![ubuntu_64-bit__localdev_](https://cloud.githubusercontent.com/assets/7142397/7800186/8ff435dc-02c6-11e5-894f-2c4598372c64.png)

I was able to restart and log into the 14.04 instance through VirtualBox, but I can no longer manage it from Test Kitchen.

```
$ kitchen converge default-ubuntu-1404
-----> Starting Kitchen (v1.4.0)
-----> Converging <default-ubuntu-1404>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 3.2.3...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
       [SSH] connection failed, retrying in 1 seconds (#<Errno::ECONNREFUSED: Connection refused - connect(2) for "127.0.0.1" port 2222>)
       [SSH] connection failed, retrying in 1 seconds (#<Errno::ECONNREFUSED: Connection refused - connect(2) for "127.0.0.1" port 2222>)
       [SSH] connection failed, retrying in 1 seconds (#<Errno::ECONNREFUSED: Connection refused - connect(2) for "127.0.0.1" port 2222>)
       [SSH] connection failed, retrying in 1 seconds (#<Errno::ECONNREFUSED: Connection refused - connect(2) for "127.0.0.1" port 2222>)
$$$$$$ [SSH] connection failed, terminating (#<Errno::ECONNREFUSED: Connection refused - connect(2) for "127.0.0.1" port 2222>)
>>>>>> Converge failed on instance <default-ubuntu-1404>.
>>>>>> Please see .kitchen/logs/default-ubuntu-1404.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSH session could not be established
>>>>>> ----------------------
```

My log file is here: https://gist.github.com/tpetchel/c4fb4215085dc9022e1a#file-default-ubuntu-1404-log

## Additional info

This consistently repos, and I was able to repo it on two separate Ubuntu host instances. I did not try from another host OS, such as MacOS or Windows. Also, if you manage only a 14.04 instance or a 12.04 instance, everything works as expected. The issue seems to stem from the two running together.
