### ISSUE TITLE
Allow to customize cpuidset for VirtualBox VMs 

### ISSUE THREAD

**Issue by jochenseeber** [test-kitchen/kitchen-vagrant#175]
In VirtualBox machines there is a cpuidset setting that is set as follows:

```
config.vm.provider :virtualbox do |v|
    v.customize ["modifyvm", :id, "--cpuidset", "00000001", "000306a9", "00020800", "80000201", "178bfbff"]
end
```

This currently cannot be modified in Test Kitchen. The driver customizations should be extended so the following works:

```
driver:
    name: vagrant
    customize:
        cpuidset: ["00000001", "000306a9", "00020800", "80000201", "178bfbff"]
```
