### ISSUE TITLE
Cannot pass parameters to winrm (vagrant)

### ISSUE THREAD

**Issue by Gray-Wind** [test-kitchen/kitchen-vagrant#187]
Hello.

I cannot pass parameter to winrm properly.
Kitchen version is 1.4.0, vagrant version is 1.7.4

Mine .kitchen.yml:

```yml
---
driver:
  name: vagrant
  customize:
    cpus: 2
    memsize: 2048

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
  - name: win2012
    driver:
      box: win2012
      communicator: winrm
      winrm:
        host: 127.0.0.1
        port: 55985

suites:
  - name: win-build
    run_list:
      - recipe[win-build::default]
```

In the Vagrantfile I receive ```c.winrm.host = 127.0.0.1``` and it could not be used because it is not a string
```
(...)win2012/Vagrantfile:5: no .<digit> floating literal anymore; put 0 before dot
           c.winrm.host = 127.0.0.1
```

Adding quotes to IP in the YML changes nothing.

I tried to replace IP address with ```localhost``` but it could not be used, too.
Output: ```undefined local variable or method `localhost' for main```
