### ISSUE TITLE
Large(ish) download times out on converge unless I login to the VM in a separate window

### ISSUE THREAD

**Issue by StFS** [test-kitchen/kitchen-vagrant#192]
I have a cookbook that installs Java via the standard "java" cookbook from the Supermarket.

I have a .kitchen.yml file with the following config:
```yaml
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_solo
  environments_path: kitchen-envs

platforms:
  - name: centos-7
    driver:
      box: our-centos-7
      box_url: https://cdn.oururl.com/our_centos-7-x86_64_virtualbox.box

suites:
# The following suite sets up a machine with a recipe that installs the Oracle JDK
  - name: common
    run_list:
      - recipe[ourcookbook::common]
    attributes: 
    provisioner:
      solo_rb:
        environment: test-kitchen
```

So basically nothing out of the ordinary.

The problem is that when I try to converge, more often than not, the converge times out after 10 minutes if I just let it run.

The weird thing is that if I do a `kitchen login common` in a separate window, the process kicks in and the installation continues. I have tested this enough times to be 99% sure that this is not a coincidence.

I thought this might be related to https://github.com/test-kitchen/test-kitchen/issues/585 so I've upgraded to the latest test-kitchen gem (1.4.2) and also set `require_chef_omnibus` to `true` to get the latest Chef but this makes no difference. I still get these weird timeouts when downloading the Oracle JDK tarball (166Mb). 

I'm on Kubuntu 14.04 using ruby 2.1.6 (via rbenv) and as I mentioned, test-kitchen 1.4.2 and Chef 12.4.1.
