### ISSUE TITLE
proxy for docker running with driver kitchen-vagrant

### ISSUE THREAD

**Issue by SydOps** [test-kitchen/kitchen-vagrant#235]
Following the document (https://docs.chef.io/config_yml_kitchen.html), I have successfully worked out with proxy setting to download packages via corporate proxy in vagrant box

```
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  http_proxy: http://10.0.0.1:3128
  https_proxy: http://10.0.0.1:3128
```
In one ansible playbook task,  I need pull docker image, I have issue to download it

     "msg": "Error pulling hub.docker.com/httpd - code: None message: unable to ping registry endpoint https://10.0.0.1:3128"

Referring https://docs.docker.com/engine/admin/systemd/, I try to add the setting in `.kitchen.yml` to provide proxy support for docker, but failed. 

```
platforms:
  - name: centos-7.2
    driver_config:
      provision_command:
        - yum -y install docker python-pip
        - pip install docker-py
        - mkdir -p /etc/systemd/system/docker.service.d
        - echo "[Service]" >> /etc/systemd/system/docker.service.d/http-proxy.conf
        - echo "Environment=\"HTTP_PROXY=http://10.0.0.1:3128/ \"">> /etc/systemd/system/docker.service.d/http-proxy.conf
        - systemctl daemon-reload
        - systemctl restart docker
      platform: centos
```

But doesn't work directly.  Then I manually `kitchen login`, and do the same change as mentioned above. running with `kitchen converge` is fine. I got all ansible playbooks installed. 

Any hints for me to correct `.kitchen.yml` to support docker with proxy?
