### ISSUE TITLE
Generated Vagrantfile has type issues

### ISSUE THREAD

**Issue by jsirex** [test-kitchen/kitchen-vagrant#236]
I'm using latest vagrant, test-kitchen, virtualbox. Nothing helps me to bring machine up:
```yaml
---
driver:
  name: vagrant
  ssh:
    insert_key: false
  customize:
    cpus: 1
    memory: 1024
```
Produces:
```ruby
Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "bento/centos-6.7"
  c.vm.hostname = "default-centos-67"
  c.ssh.insert_key = "false"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
    p.customize ["modifyvm", :id, "--cpus", "1"]
    p.customize ["modifyvm", :id, "--memory", "1024"]
  end
end
```

Here is false as string ```"false"```

Relates to #130
