### ISSUE TITLE
Vagrant 1.9.1 does not enable additional network interfaces for centos 7 

### ISSUE THREAD

**Issue by jslusher** [test-kitchen/kitchen-vagrant#287]
I have a .kitchen.yml that used to enable additional network interfaces:
```
    driver:
      require_chef_omnibus: 12.18.31
      name: vagrant
      vm_hostname: myhost
    ...
      network:
        - ["private_network", {ip: "10.100.0.53"}]
```

With vagrant 1.9.1 a kitchen create has the network interface configured, but in a DOWN state. an `ifup enp0s8` will bring the interface up with the proper IP address. 

Vagrant 1.8.7 does not have this problem.
