### ISSUE TITLE
adding more than one disk to a box

### ISSUE THREAD

**Issue by goblin23** [test-kitchen/kitchen-vagrant#288]
via
```
driver:
  customize:
    createhd:
      filename: /tmp/disk1.vmdk
      size: 1024
    storageattach:
      storagectl: SATA Controller
      port: 1
      device: 0
      type: hdd
      medium: /tmp/disk1.vmdk
```
you can only add one disk.
 it would be nice to be able to create and attach multiple disks
