### ISSUE TITLE
Vagrant Hyper-V Support

### ISSUE THREAD

**Issue by michaeltlombardi** [test-kitchen/kitchen-vagrant#297]
I know that there's a separate hyper-v plugin for test kitchen, but now that [Vagrant supports Hyper-V as a virtualization provider out of the box](https://www.vagrantup.com/docs/hyperv/), should we be able to use Hyper-V vagrant boxes with this plugin?

I'm exploring the option now, but it seems broken on virtual-switch selection. I'll do up a full report if this is something we're interested in supporting via this plugin.

**Comment by mwrock** [comment]
I use Hyper-V with kitchen-vagrant but agree that things get difficult if you have more than one virtual switch and kitchen does not allow you to enter which switch to use. I know there is a vagrant configuration to choose and you should be able to provide a custom Vagrantfile erb to set it from kitchen. I have not done that but its a lead to investigate.

**Comment by michaeltlombardi** [comment]
I'll look into that route and post back once I have a functional config. I'm using your vagrant box currently, so thanks for providing that!

**Comment by michaeltlombardi** [comment]
# Fix for Hyper-V Switch Choice
```yaml
      network:
        - ["private_network", {bridge: "Guest"}]
```

That worked, but now I fail on renaming the VM despite not having any settings in the `yml` for a vm name change.

## Full YAML

```yaml
---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: mwrock/Windows2012R2
    driver:
      provider: hyperv
      memory: 2048
      cpus: 2
      communicator: winrm
      network:
        - ["private_network", {bridge: "Guest"}]

suites:
  - name: default
    run_list:
      - recipe[learn_chef_iis::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:

```

**Comment by michaeltlombardi** [comment]
Well, I deleted all of the logs and the artifacts from previous attempts (erased everything in `.kitchen/kitchen-vagrant/`) and tried again with the debug flag and everything worked fine. 

Did a `kitchen destroy ; kitchen create` and it [seems to be broken again](https://gist.github.com/michaeltlombardi/f857ec212a111b6ba586f68b2c9aa30d). The problem seems to be the auto generated `Vagrantfile` [setting the vmhost name for some reason](https://gist.github.com/michaeltlombardi/f857ec212a111b6ba586f68b2c9aa30d#file-vagrantfile-L4) to `default-mwrock-Windows2012R2.vagrantup.com`

I'm going to try setting `vm_hostname` explicitly.

**Comment by michaeltlombardi** [comment]
It looks like the final edit to the hostname cleared things up - [results here].

So far as I can tell, vagrant with Hyper-V works fine with this plugin but is undocumented and has some non-obvious gotchas which should be pointed out:

1. Because `kitchen create` is non-interactive, you **must** configure the `network` option of the `driver` if you have more than one virtual switch.
2. Test-Kitchen seems to pull a hostname including the box's url if you don't specify one for Hyper-V, so you must also configure the `vm_hostname` option of the `driver`.
3. I found that you seem to have to specify the `transport` setting even if the box defaults to WinRM to force it around trying SSH.

I'm glad to open another issue around documentation and contribute wherever necessary. This also indicates that the [Learn Chef tutorial for Test-Kitchen](https://learn.chef.io/tutorials/local-development/) could be updated to include a `Vagrant and Hyper-V` option.

**Comment by michaeltlombardi** [comment]
Hmm, tried a kitchen converge and got some weird behavior ([diagnostic here](https://gist.github.com/michaeltlombardi/349dceb71f0119334811bf49f19236f1)) - `kitchen converge` doesn't seem to install the chef-client [as expected](https://learn.chef.io/tutorials/local-development/windows/virtualbox/apply-a-cookbook/#step4) - no errors or failures, the step `Installing Chef Omnibus` just doesn't come up.

```
PS C:\dev\AutoMon\chef-repo> kitchen converge
-----> Starting Kitchen (v1.15.0)
-----> Converging <default-mwrock-Windows2012R2>...
       Preparing files for transfer
       Preparing dna.json
       Preparing cookbooks from project directory
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
       Transferring files to <default-mwrock-Windows2012R2>
       Finished converging <default-mwrock-Windows2012R2> (0m33.44s).
-----> Kitchen is finished. (0m36.48s)
```

I was able to verify that it did not install the chef client:

```
PS C:\dev\AutoMon\chef-repo> kitchen exec -c 'get-command ch*'
-----> Execute command on default-mwrock-Windows2012R2.

       CommandType     Name                                               ModuleName
       -----------     ----                                               ----------
       Alias           chdir -> Set-Location
       Function        choco                                              Boxstarte...
       Function        choco                                              Boxstarte...
       Cmdlet          Checkpoint-Computer                                Microsoft...
       Cmdlet          Checkpoint-IscsiVirtualDisk                        IscsiTarget
       Application     change.exe
       Application     changepk.exe
       Application     chcp.com
       Application     CheckNetIsolation.exe
       Application     chglogon.exe
       Application     chgport.exe
       Application     chgusr.exe
       Application     chkdsk.exe
       Application     chkntfs.exe
       Application     choco.exe
       Application     chocolatey.exe
       Application     choice.exe
```

This may not be directly related to the plugin, but keeping it in this thread for anyone who tries to go this route and hits the same pitfalls.

@mwrock, have you seen this before?

**Comment by michaeltlombardi** [comment]
Yup, that was it. The updated config below worked, had to specify `os_type` and `shell_type` under `platforms`:

## Functional Configuration
```yaml
---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

transport:
  name: winrm
  elevated: true

platforms:
  - name: mwrock/Windows2012R2
    os_type: windows
    shell_type: powershell 
    driver:
      provider: hyperv
      memory: 2048
      cpus: 2
      vm_hostname: chef-fu
      network:
        - ["private_network", {bridge: "Guest"}]

suites:
  - name: default
    run_list:
      - recipe[learn_chef_iis::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:

```

**Comment by mwrock** [comment]
One thing to note is that you can omit the `os_type` and `shell_type` if your platform name begins with `win`. So:
```
platforms:
  - name: Windows2012R2
    driver:
      box: mwrock/Windows2012R2
      provider: hyperv
      memory: 2048
      cpus: 2
      vm_hostname: chef-fu
      network:
        - ["private_network", {bridge: "Guest"}]
```
