### ISSUE TITLE
box_download_ca_cert seems to not be set in generated Vagrantfile

### ISSUE THREAD

**Issue by daks** [test-kitchen/kitchen-vagrant#301]
We are using test-kitchen with some custom build boxes stored in a HTTPS server which have a custom certificate (internal CA). When giving kitchen the URL for the JSON file and the CA certificate, kitchen fails with an error about insecure certificate.

The relevant section in .kitchen.yml is
```
driver:
  name: vagrant
  box_url: https://srv.domain.tld/vagrant/jessie64.json
  box_download_ca_cert: 'ca-cert.pem'
```
but the generated Vagrantfile looks like
```
Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "jessie64"
  c.vm.box_url = "https://srv.domain.tld/vagrant/jessie64.json"
```
The c.vm.box_download_ca_cert = 'ca-cert.pem' is missing.

If I create manually a Vagrantfile with these directives, Vagrant starts well.
