### ISSUE TITLE
ssh connection between cloud init and kitchen outside cloud environment

### ISSUE THREAD

**Issue by aidda** [test-kitchen/kitchen-vagrant#308]
I have a customize centos image, which is a qcow2 image. Now I want to run my cookbook but I have a trouble to make an ssh connection between kitchen and machine. this is kitchen.yml
```
---
driver-plugin:
  name: vagrant-libvirt

driver:
  name: vagrant


transport:
  username: cloud-user
  ssh_key: /home/aida/Documents/chef-solo/cookbooks/gtd_buildhost/keys/libvirt.pub

provisioner:
  name: chef_solo

platforms:
  - name: rhel7
    driver_config:
      box: qcow-libvrit
      box_url: file:///home/aida/Documents/packer/builds/libvirt-centos7.box
#cloud-config
users:
  - name: root
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    user-data: /home/aida/Documents/chef-solo/cookbooks/gtd_buildhost/keys/user-data

suites:
  - name: default
    run_list:
      - recipe[gtd_buildhost::default]
    attributes:
```
and when I do the` kitchen create `, I received this:

```
-----> Starting Kitchen (v1.16.0)
-----> Creating <default-rhel7>...
       Bringing machine 'default' up with 'libvirt' provider...
       ==> default: Starting domain.
       ==> default: Waiting for domain to get an IP address...
       ==> default: Waiting for SSH to become available...
```
and it hanged on ssh. I know I have to pass a key from my machine to guest but I don't know how I can to it in the kitchen.yml.
