### ISSUE TITLE
kitchen list fail in vagrant --version step with STDERR: stdin is not a tty with Vagrant 1.9.7 on Windows 10

### ISSUE THREAD

**Issue by joelhandwell** [test-kitchen/kitchen-vagrant#320]
I generated kitchen.yml with command ```chef generate cookbook mycookbook``` as following:

```yml
---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[mycookbook::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:

```

Then I run kitchen list and got following:

```
> kitchen list
-----> Starting Kitchen (v1.16.0)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ShellOut::ShellCommandFailed
>>>>>> Message: Expected process to exit with [0], but received '1'
---- Begin output of vagrant --version ----
STDOUT:
STDERR: stdin is not a tty
---- End output of vagrant --version ----
Ran vagrant --version returned 1
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

Here is debug output https://gist.github.com/joelhandwell/f5c324ee73f0ccf0d0474a0ea27764e0

Hoped this would work out of the box. 
My environment is: 
ChefDK 2.0.28
Test Kitchen 1.16.0
Vagrant 1.9.7
Windows 10

Could be related with vagrant tty config? https://github.com/mitchellh/vagrant/issues/1673
