### ISSUE TITLE
[Feature] - Add support for other vagrant hypervisor plug-ins required variables

### ISSUE THREAD

**Issue by chicolatino** [test-kitchen/kitchen-vagrant#350]
I'm using the [vagrant-vmware-esxi](https://github.com/josenk/vagrant-vmware-esxi) plugin as a provider but running into issues when I try to pass parameters that are specific to the provider (not vm customizations)

My feature suggestion would be to have a mechanism to pass parameters to the provider in a generic way that could be leveraged by other providers using key value pairs that are rendered in the Vagrantfile under "c.vm.provider :provider do |p|"

For example, the vagrant-vmware-esxi provider requires the following variables to work (a few other parameters are optional but having a generic way would allow for them to be used):
- esxi_hostname
- esxi_username
- esxi_password

This should show up as:

```
c.vm.provider :vmware_esxi do |p|
  p.esxi_hostname = 'hostname'
  p.esxi_username = 'username'
  p.esxi_password = 'prompt:'
```
in the generated Vagrant file.

It could be implemented along these lines:

```
driver:
  name: vagrant
  provider: other_provider_name_here
  provider_options:
    - option1: "value1"
    - option2: "value2"
    - option3: "value3"
```

Wish I could implement this myself but I'm not a coder (more of a sysadmin).

Thanks!
