### ISSUE TITLE
Vagrant 2.1.4 breaks `require`, replace with `load`

### ISSUE THREAD

**Issue by y0y0z** [test-kitchen/kitchen-vagrant#371]
i am using [`vagrantfiles`](https://github.com/test-kitchen/kitchen-vagrant#-vagrantfiles) as follows
```yaml
platforms:
    driver:
      vagrantfiles:
        - Vagrantfile_extension.rb
```
```bash
$ cat Vagrantfile_extension.rb
Vagrant.configure('2') do |config|
  config.vagrant.plugins = ['vagrant-disksize']
  config.disksize.size = '50GB'
end
```

when i execute `kitchen converge`, `vagrant-disksize` is not invoked.
i used the flowing command to launch `vagrant` directly with the `Vagrantfile` generated by `kitchen`.
```bash
$ VAGRANT_VAGRANTFILE=.kitchen/kitchen-vagrant/foo-ubuntu-1604/Vagrantfile vagrant up
```
but again, `vagrant-diskzie` was not invoked.
i modified the `Vagrantfile` generated by `kitchen`, and replaced [`require` with `load`](https://github.com/test-kitchen/kitchen-vagrant/blob/master/templates/Vagrantfile.erb#L2) and then `vagrant-disksize` was invoked.

some more technical information
```bash
$ vagrant --version
Vagrant 2.1.4

$ bundle exec kitchen --version
Test Kitchen version 1.23.2

$ cat Gemfile.lock | grep 'kitchen-vagrant ('
    kitchen-vagrant (1.3.3)
```

shall i file a bug?
can someone confirm this issue?

**Comment by cheeseplus** [comment]
Based on the formatting of the snippet, the indentation is off which means YAML won't see the key in the right place.

```
platforms:
  driver:
    vagrantfiles:
    - Vagrantfile_extension.rb
```

Please try checking the indentation first, if that's still a problem we can investigate.
