### ISSUE TITLE
kitchen converage error

### ISSUE THREAD

**Issue by spandanareddyt** [test-kitchen/kitchen-vagrant#406]
```
---
driver:
  name: vagrant
  provider: hyperv
  network:  
         -["public_network", bridge: "vagrant"]
## The forwarded_port port feature lets you connect to ports on the VM guest via
## localhost on the host.
## see also: https://www.vagrantup.com/docs/networking/forwarded_ports.html

#  network:
#    - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

  ## product_name and product_version specifies a specific Chef product and version to install.
  ## see the Chef documentation for more details: https://docs.chef.io/config_yml_kitchen.html
  #  product_name: chef
  #  product_version: 15

verifier:
  name: inspec

platforms:
  #- name: ubuntu-18.04
  - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[effectivelamp::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
```

dis is the code and the error is
![62572199-c9bef280-b8b0-11e9-8d3a-713d2a155578](https://user-images.githubusercontent.com/53507073/62600582-dd984200-b90c-11e9-9155-ff2fd927b859.jpeg)
