### ISSUE TITLE
SMB File Shares are hanging

### ISSUE THREAD

**Issue by Nickolaitc** [test-kitchen/kitchen-vagrant#417]
Hello,

I am attempting some Chef Kitchen testing with kitchen-vagrant and hyperv and encountering issues with the SMB share.  

My kitchen file:
```
---
driver:
  name: vagrant
  provider: hyperv
  cache_directory: false
  network:
  - ["public_network", bridge: "Default Switch"]
  customize: 
     memory: 5000
     cpus: 2
     
provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

transport:
  name: winrm
  elevated: true

platforms:
  - name: Windows
    driver:
      box: mwrock/Windows2012R2
    

suites:
  - name: testing
    driver:
      synced_folders:
        - ["C:\\MyCoolStuff\\Chef\\ChefEntPack\\certificates", "C:\\certificates"]
        - ["C:\\MyCoolStuff\\Chef\\ChefEntPack\\installers", "C:\\setups"]
        - ["C:\\MyCoolStuff\\Chef\\ChefEntPack\\license", "C:\\license"]
```
The output I am getting every time:
```
Vagrant requires administrator access for pruning SMB shares and
may request access to complete removal of stale shares.
==> default: Preparing SMB shared folders...
    default: You will be asked for the username and password to use for the SMB
    default: folders shortly. Please use the proper username/password of your
    default: account.
    default:
    default: Username:     default: Password (will be hidden):
Error! Your console doesn't support hiding input. We'll ask for
input again below, but we WILL NOT be able to hide input. If this
is a problem for you, ctrl-C to exit and fix your stdin.
     default: Password (will be hidden):
Vagrant requires administrator access to create SMB shares and
may request access to complete setup of configured shares.
==> default: Mounting SMB shared folders...
    default: C:/MyCoolStuff/Chef/ChefEntPack/certificates => C:\certificates
STDERR: The following WinRM command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

cmdkey /add:MYIPADDRESS /user: /pass:""
```
I attempted to incorporate smb_user smb_password - https://www.vagrantup.com/docs/synced-folders/smb.html  but thinking this won't do any good.

I also disabled UAC on the host system, but this doesn't change anything.

Any help with this would be greatly appreciated as I am stuck!
