### ISSUE TITLE
Add support for provision_command

### ISSUE THREAD

**Issue by berniedurfee** [test-kitchen/kitchen-vagrant#78]
The kitchen-docker driver has a 'provision_command' attribute that allows you to specifically set the command executed when provisioning the Chef client. This is much more flexible than just setting the URL for the script and would really help those of us trapped behind a corporate firewall.

**Comment by SydOps** [comment]
Seems still in progress.

**Comment by Lirt** [comment]
For anybody looking for hotfix, you can follow this guide http://www.elmund.io/2015/07/05/run-a-script-on-a-test-kitchen-vm-before-converge-starts/

Basically if you specify driver in .kitchen.yml like this:

```yml
platforms:
   - name: fedora-27
     driver:
       provision: True
       vagrantfiles:
         - fedora27_provision.rb
```

And then you specify provisioning file like that, you can for do preprovisioning steps:

```ruby
Vagrant.configure(2) do |config|
  config.vm.provision "shell", inline: <<-SHELL
     sudo dnf install -y python2
  SHELL
end
```
