### ISSUE TITLE
Forward multiple ports?

### ISSUE THREAD

**Issue by ChrisLundquist** [test-kitchen/kitchen-vagrant#9]
previously,

``` yaml
driver_config:
  forward_port:
    - [4444, 4444]
    - [5555, 5555]
```

would forward both ports.

I expected something like

``` yaml
driver_config:
  network:
    forwarded_port:
      - { guest: 5555, host: 5555}
      - { guest: 4444, host: 4444}
```

or

``` yaml
driver_config:
  network:
   - forwarded_port:
       guest: 5555
       host: 5555
   - forwarded_port:
       guest: 4444
       host: 4444
```

to work, but it produces things like

`c.vm.network(:[:forwarded_port, [{:guest=>4444, :host=>4444}]], )`
